# Generated by Django 4.2 on 2025-03-10 18:08

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages')),
                ('pdfFile', models.FileField(blank=True, null=True, upload_to='packages/files')),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
