# Generated by Django 4.2 on 2025-03-10 18:22

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_package_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('cid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('requirements', tinymce.models.HTMLField(blank=True, null=True)),
                ('application_process', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
