# Generated by Django 4.2 on 2025-03-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='mainBanner',
            field=models.ImageField(null=True, upload_to='services'),
        ),
    ]
