# Generated by Django 4.2 on 2025-05-20 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_service_mainbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='website.service'),
        ),
    ]
